---
####
# Updating
##
- name: Update package source lists
  become: yes
  apt:
    update_cache: yes
- name: Upgrade the system packages and kernel
  become: yes
  apt:
    upgrade: dist
####
# Install
##
- name: Install additional software packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - bridge-utils
    - debootstrap
    - ifenslave
    - ifenslave-2.6
    - lsof
    - lvm2
    - ntp
    - ntpdate
    - openssh-server
    - sudo
    - tcpdump
    - vlan

####
# Other
##
- name: Install additional software packages
  become: yes
  raw: echo '{{ item }}' >> /etc/modules
  with_items:
    - bonding
    - 8021q

- name: ntp service restart
  become: yes
  service:
    name: ntp
    state: restarted

####
# Copy update hostnames & ssh keys
# TODO
##
- name: build hosts file
  become: true
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].internal_ip }} {{item}}" state=present
  when:
    - hostvars[item].internal_ip is defined
  with_items:
    - "{{ groups['all'] }}"

