---
canary: 'pio pio'

targets:
  virtualbox:
      vbox_username: 'vagrant'
      vbox_boxtype: 'bento/ubuntu-16.04'
      vbox_iprange: '10.5.0'
      vbox_ipoffset: 10

machines:
  - vm:
      hostname: 'template01'
      name: 'cdev::myproj::01'
      hw:
        cpus: '2'
        ram: '2048'
  - vm:
      hostname: 'template02'
      name: 'cdev::myproj::02'
      hw:
        cpus: '2'
        ram: '2048'

provisioner:
  ansible:
    limit: "all"
    playbook: "cluster_template.yml"
    groups: ""
    host_vars: ""

